# Generated by Django 2.2.1 on 2019-05-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190516_0855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpositionapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpositionapplication',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userpositionapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='position',
            name='length',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserPositionApplication',
        ),
    ]
