# Generated by Django 2.2 on 2019-05-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_auto_20190501_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='applicant_requirements',
            new_name='requirements',
        ),
    ]
