# Generated by Django 2.2 on 2019-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, choices=[('PY', 'Python'), ('JV', 'Java'), ('JS', 'JavaScript'), ('PHP', 'Php'), ('RU', 'Ruby')], default='', max_length=50, null=True),
        ),
    ]
