# Generated by Django 2.2.1 on 2019-05-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_selfchoosenskill_userprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, choices=[('PY', 'Python'), ('JV', 'Java'), ('JS', 'JavaScript'), ('PHP', 'Php'), ('RU', 'Ruby'), ('DES', 'Designer'), ('AN', 'Android'), ('WP', 'WordPress'), ('IOS', 'iOS')], default='', max_length=50),
        ),
    ]
