# Generated by Django 2.2.1 on 2019-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190517_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
